databases:
  - name: MeetingMinutes
    user: MeetingMinutes
    plan: free
    region: oregon

services:
  - type: web
    name: MeetingMinutes
    plan: free
    region: ohio
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: MeetingMinutes
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false